In [1]:
import numpy as np

In [19]:
arr1 = np.array([[4,5,8],[7,8,9.0]])

In [20]:
arr1,arr1.shape

(array([[4., 5., 8.],
        [7., 8., 9.]]),
 (2, 3))

In [21]:
arr1.dtype

dtype('float64')

In [17]:
# type conversion
np.arange(10).astype(float)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [22]:
arr1 * 9

array([[36., 45., 72.],
       [63., 72., 81.]])

In [24]:
r1 = np.arange(10)
r2 = np.arange(10,20)
r3 = np.arange(20,30)
lst = [r1,r2,r3]
for i in range(len(lst)):
    print(lst[i].shape)

(10,)
(10,)
(10,)


In [25]:
m = np.array(lst)

In [26]:
m.shape

(3, 10)